### ISSUE TITLE
Benchmark 1m x 1m 100 times in a row

### ISSUE THREAD

**Issue by hardbyte** [data61/anonlink-entity-service#324]
With one k8s deployment run the [benchmarks](https://github.com/n1analytics/entity-service/tree/develop/deployment/jobs/benchmark) with 1M x 1M matching - repeat 100 times (not running benchmarks in parallel).

```
apiVersion: batch/v1
kind: Job
metadata:
  name: entityservice-benchmark-repeat
spec:
  completions: 100
  parallelism: 1
  ...
```

I tried last night and it failed after 12 successes. When it works the output is like this:
```
 {'experiments': [{'experiment': {'sizes': ['100K', '100K'], 'threshold': 0.95},
                  'match_results': {'fn': 31899,
                                    'fp': 0,
                                    'tn': 33334,
                                    'tp': 34767},
                  'sizes': {'size_a': 100000, 'size_b': 100000},
                  'status': 'completed',
                  'threshold': 0.95,
                  'timings': {'added:': '2019-02-14T06:42:11.482689+00:00',
                              'completed': '2019-02-14T06:42:23.712568+00:00',
                              'runtime': 12.14382,
                              'started': '2019-02-14T06:42:11.568748+00:00'}},
                 {'experiment': {'sizes': ['100K', '1M'], 'threshold': 0.85},
                  'match_results': {'fn': 3268,
                                    'fp': 8021,
                                    'tn': 29810,
                                    'tp': 58901},
                  'sizes': {'size_a': 100000, 'size_b': 1000000},
                  'status': 'completed',
                  'threshold': 0.85,
                  'timings': {'added:': '2019-02-14T06:42:36.634613+00:00',
                              'completed': '2019-02-14T06:44:16.393435+00:00',
                              'runtime': 99.646248,
                              'started': '2019-02-14T06:42:36.747187+00:00'}},
                 {'experiment': {'sizes': ['1M', '1M'], 'threshold': 0.95},
                  'match_results': {'fn': 317156,
                                    'fp': 0,
                                    'tn': 333334,
                                    'tp': 349510},
                  'sizes': {'size_a': 1000000, 'size_b': 1000000},
                  'status': 'completed',
                  'threshold': 0.95,
                  'timings': {'added:': '2019-02-14T06:44:42.540882+00:00',
                              'completed': '2019-02-14T07:00:00.405531+00:00',
                              'runtime': 917.76368,
                              'started': '2019-02-14T06:44:42.641851+00:00'}}],
 'server': 'https://anonlink.data61.xyz',
 'version': {'anonlink': '0.10.0',
             'entityservice': 'v1.9.4',
             'python': '3.6.5'}} 
``` 

The failure appears in k8s when creating a new benchmarking pod (from the job):

```
MountVolume.WaitForAttach failed for volume "pvc-464eedca-d38c-11e8-80da-0a5206e344ae" : WaitForAttach failed for AWS Volume "aws://ap-southeast-2c/vol-056d51258739eb798": devicePath is empty

Unable to mount volumes for pod "entityservice-benchmark-repeat-6pptr_default(d9e95f18-3041-11e9-a695-0aef446cd8aa)": timeout expired waiting for volumes to attach or mount for pod "default"/"entityservice-benchmark-repeat-6pptr". list of unmounted volumes=[data-volume]. list of unattached volumes=[experiments-volume data-volume default-token-hdz67] 
```

cc @peterhassall would you have any pointers?

**Comment by gusmith** [comment]
The benchmarking is changing, and instead of creating 100 k8s jobs, we loop in python, reducing complexity of k8s (reduce the number of possible error due to deployment of the jobs).

So during the weekend of the 17th of August 2019, I started a 100 runs of the 1M*1M experiement.
It failed after 17 runs.

Here are the logs containing errors (showing only the first observed error)

## Received from the benchmark
```
WARNING:experiment '{'sizes': ['1M', '1M'], 'threshold': 0.9, 'repetition': 100, 'rep': 18}' failed: Traceback (most recent call last):
  File "benchmark.py", line 270, in run_single_experiment
    credentials['result_token'], timeout=config['timeout'])
  File "/usr/local/lib/python3.7/site-packages/clkhash/rest_client.py", line 130, in wait_for_run
    for status in watch_run_status(server, project, run, apikey, timeout, update_period):
  File "/usr/local/lib/python3.7/site-packages/clkhash/rest_client.py", line 173, in watch_run_status
    status = run_get_status(server, project, run, apikey)
  File "/usr/local/lib/python3.7/site-packages/clkhash/rest_client.py", line 113, in run_get_status
    return _handle_json_response(response, "Run Status Error", 200)
  File "/usr/local/lib/python3.7/site-packages/clkhash/rest_client.py", line 31, in _handle_json_response
    raise ServiceError(failure_message, response)
clkhash.rest_client.ServiceError: Run Status Error
Status Code: 500
Server Message:
{
  "detail": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",
  "status": 500,
  "title": "Internal Server Error",
  "type": "about:blank"
} 
```

## Server status

Not in a happy state:
```
$ curl https://benchmark.es.data61.xyz/api/v1/status
{
  "detail": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",
  "status": 500,
  "title": "Internal Server Error",
  "type": "about:blank"
}
```

## API
### Flask container

Not much logs there, but it has restarted 350 times and seems to be continuously increasing even now, 2 days after the failure

## Workers

There are two of them.
### Worker 1
```
[2019-08-16 15:19:30,809: INFO/MainProcess] Received task: entityservice.tasks.comparing.compute_filter_similarity[b1cde875-a9ac-47ea-8080-009060a0d753]  
[2019-08-16 15:19:30,877: WARNING/ForkPoolWorker-6] [2m2019-08-16T15:19:30.877369Z[0m [[33m[1mwarning  [0m] [1mfallback connecting to default postgres db[0m [[34m[1mentityservice.database.util[0m] [36mdatabase[0m=[35mpostgres[0m [36mhost[0m=[35mbenchmark-es-data61-xyz-db[0m [36muser[0m=[35mpostgres[0m
[2019-08-16 15:19:30,901: WARNING/ForkPoolWorker-6] [2m2019-08-16T15:19:30.901135Z[0m [[33m[1mwarning  [0m] [1mCan't connect to database     [0m [[34m[1mentityservice.database.util[0m]
[2019-08-16 15:19:30,924: WARNING/ForkPoolWorker-6] [2m2019-08-16T15:19:30.924419Z[0m [[31m[1merror    [0m] [1mUnexpected exception raised in task b1cde875-a9ac-47ea-8080-009060a0d753[0m [[34m[1mentityservice.tasks[0m] 
Traceback (most recent call last):
  File "/var/www/entityservice/database/util.py", line 38, in connect_db
    conn = psycopg2.connect(database=db, user=user, password=pw, host=host)
  File "/usr/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not fork new process for connection: Resource temporarily unavailable

could not fork new process for connection: Resource temporarily unavailable


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/entityservice/database/util.py", line 41, in connect_db
    conn = psycopg2.connect(database='postgres', user=user, password=pw, host=host)
  File "/usr/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not fork new process for connection: Resource temporarily unavailable

could not fork new process for connection: Resource temporarily unavailable


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/www/entityservice/tasks/base_task.py", line 87, in __call__
    return super(TracedTask, self).__call__(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/entityservice/tasks/comparing.py", line 120, in compute_filter_similarity
    with DBConn() as db:
  File "/var/www/entityservice/database/util.py", line 68, in __init__
    self.conn = conn if conn is not None else connect_db()
  File "/var/www/entityservice/database/util.py", line 45, in connect_db
    raise ConnectionError("Issue connecting to database")
ConnectionError: Issue connecting to database
```

### Worker 2

```
[2019-08-16 15:19:30,765: INFO/MainProcess] Received task: entityservice.tasks.comparing.compute_filter_similarity[2f13ee97-e360-4ce1-8d23-8ce4b8a046c8]  
[2019-08-16 15:19:30,822: WARNING/ForkPoolWorker-7] [2m2019-08-16T15:19:30.821882Z[0m [[33m[1mwarning  [0m] [1mfallback connecting to default postgres db[0m [[34m[1mentityservice.database.util[0m] [36mdatabase[0m=[35mpostgres[0m [36mhost[0m=[35mbenchmark-es-data61-xyz-db[0m [36muser[0m=[35mpostgres[0m
[2019-08-16 15:19:30,858: WARNING/ForkPoolWorker-4] [2m2019-08-16T15:19:30.858441Z[0m [[33m[1mwarning  [0m] [1mfallback connecting to default postgres db[0m [[34m[1mentityservice.database.util[0m] [36mdatabase[0m=[35mpostgres[0m [36mhost[0m=[35mbenchmark-es-data61-xyz-db[0m [36muser[0m=[35mpostgres[0m
[2019-08-16 15:19:30,875: WARNING/ForkPoolWorker-7] [2m2019-08-16T15:19:30.875622Z[0m [[33m[1mwarning  [0m] [1mCan't connect to database     [0m [[34m[1mentityservice.database.util[0m]
[2019-08-16 15:19:30,877: WARNING/ForkPoolWorker-4] [2m2019-08-16T15:19:30.876888Z[0m [[33m[1mwarning  [0m] [1mCan't connect to database     [0m [[34m[1mentityservice.database.util[0m]
[2019-08-16 15:19:30,919: WARNING/ForkPoolWorker-7] [2m2019-08-16T15:19:30.919307Z[0m [[31m[1merror    [0m] [1mUnexpected exception raised in task b1a181d1-ba7d-495b-a9b7-936368680d0a[0m [[34m[1mentityservice.tasks[0m] 
Traceback (most recent call last):
  File "/var/www/entityservice/database/util.py", line 38, in connect_db
    conn = psycopg2.connect(database=db, user=user, password=pw, host=host)
  File "/usr/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not fork new process for connection: Resource temporarily unavailable

could not fork new process for connection: Resource temporarily unavailable


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/entityservice/database/util.py", line 41, in connect_db
    conn = psycopg2.connect(database='postgres', user=user, password=pw, host=host)
  File "/usr/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not fork new process for connection: Resource temporarily unavailable

could not fork new process for connection: Resource temporarily unavailable


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/www/entityservice/tasks/base_task.py", line 87, in __call__
    return super(TracedTask, self).__call__(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/entityservice/tasks/comparing.py", line 120, in compute_filter_similarity
    with DBConn() as db:
  File "/var/www/entityservice/database/util.py", line 68, in __init__
    self.conn = conn if conn is not None else connect_db()
  File "/var/www/entityservice/database/util.py", line 45, in connect_db
    raise ConnectionError("Issue connecting to database")
ConnectionError: Issue connecting to database
[2019-08-16 15:19:30,919: ERROR/ForkPoolWorker-7] Task entityservice.tasks.comparing.compute_filter_similarity[b1a181d1-ba7d-495b-a9b7-936368680d0a] raised unexpected: ConnectionError('Issue connecting to database',)
Traceback (most recent call last):
  File "/var/www/entityservice/database/util.py", line 38, in connect_db
    conn = psycopg2.connect(database=db, user=user, password=pw, host=host)
  File "/usr/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not fork new process for connection: Resource temporarily unavailable

could not fork new process for connection: Resource temporarily unavailable
```

## High Memory Worker

Only one of them.

```
[2019-08-16 15:19:30,765: INFO/MainProcess] Received task: entityservice.tasks.comparing.compute_filter_similarity[2f13ee97-e360-4ce1-8d23-8ce4b8a046c8]  
[2019-08-16 15:19:30,822: WARNING/ForkPoolWorker-7] [2m2019-08-16T15:19:30.821882Z[0m [[33m[1mwarning  [0m] [1mfallback connecting to default postgres db[0m [[34m[1mentityservice.database.util[0m] [36mdatabase[0m=[35mpostgres[0m [36mhost[0m=[35mbenchmark-es-data61-xyz-db[0m [36muser[0m=[35mpostgres[0m
[2019-08-16 15:19:30,858: WARNING/ForkPoolWorker-4] [2m2019-08-16T15:19:30.858441Z[0m [[33m[1mwarning  [0m] [1mfallback connecting to default postgres db[0m [[34m[1mentityservice.database.util[0m] [36mdatabase[0m=[35mpostgres[0m [36mhost[0m=[35mbenchmark-es-data61-xyz-db[0m [36muser[0m=[35mpostgres[0m
[2019-08-16 15:19:30,875: WARNING/ForkPoolWorker-7] [2m2019-08-16T15:19:30.875622Z[0m [[33m[1mwarning  [0m] [1mCan't connect to database     [0m [[34m[1mentityservice.database.util[0m]
[2019-08-16 15:19:30,877: WARNING/ForkPoolWorker-4] [2m2019-08-16T15:19:30.876888Z[0m [[33m[1mwarning  [0m] [1mCan't connect to database     [0m [[34m[1mentityservice.database.util[0m]
[2019-08-16 15:19:30,919: WARNING/ForkPoolWorker-7] [2m2019-08-16T15:19:30.919307Z[0m [[31m[1merror    [0m] [1mUnexpected exception raised in task b1a181d1-ba7d-495b-a9b7-936368680d0a[0m [[34m[1mentityservice.tasks[0m] 
Traceback (most recent call last):
  File "/var/www/entityservice/database/util.py", line 38, in connect_db
    conn = psycopg2.connect(database=db, user=user, password=pw, host=host)
  File "/usr/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not fork new process for connection: Resource temporarily unavailable

could not fork new process for connection: Resource temporarily unavailable


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/entityservice/database/util.py", line 41, in connect_db
    conn = psycopg2.connect(database='postgres', user=user, password=pw, host=host)
  File "/usr/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not fork new process for connection: Resource temporarily unavailable

could not fork new process for connection: Resource temporarily unavailable


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/www/entityservice/tasks/base_task.py", line 87, in __call__
    return super(TracedTask, self).__call__(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/entityservice/tasks/comparing.py", line 120, in compute_filter_similarity
    with DBConn() as db:
  File "/var/www/entityservice/database/util.py", line 68, in __init__
    self.conn = conn if conn is not None else connect_db()
  File "/var/www/entityservice/database/util.py", line 45, in connect_db
    raise ConnectionError("Issue connecting to database")
ConnectionError: Issue connecting to database
[2019-08-16 15:19:30,919: ERROR/ForkPoolWorker-7] Task entityservice.tasks.comparing.compute_filter_similarity[b1a181d1-ba7d-495b-a9b7-936368680d0a] raised unexpected: ConnectionError('Issue connecting to database',)
Traceback (most recent call last):
  File "/var/www/entityservice/database/util.py", line 38, in connect_db
    conn = psycopg2.connect(database=db, user=user, password=pw, host=host)
  File "/usr/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not fork new process for connection: Resource temporarily unavailable

could not fork new process for connection: Resource temporarily unavailable
```

## DB

```
2019-08-16 06:58:43.329 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-08-16 06:58:43.329 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2019-08-16 06:58:43.334 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2019-08-16 06:58:43.344 GMT [213] LOG:  database system was shut down at 2019-08-16 06:58:42 GMT
2019-08-16 06:58:43.348 GMT [1] LOG:  database system is ready to accept connections
2019-08-16 15:19:23.417 GMT [1] LOG:  could not fork new process for connection: Resource temporarily unavailable
2019-08-16 15:19:23.461 GMT [1] LOG:  could not fork new process for connection: Resource temporarily unavailable
[...]
```
The last line is repeated a large number of times up to the moment it becomes:
```
2019-08-16 15:19:54.950 GMT [6909] LOG:  unexpected EOF on client connection with an open transaction
2019-08-16 15:19:54.950 GMT [6636] LOG:  unexpected EOF on client connection with an open transaction
2019-08-16 15:20:02.630 GMT [7331] FATAL:  sorry, too many clients already
2019-08-16 15:20:02.631 GMT [7332] FATAL:  sorry, too many clients already
2019-08-16 15:20:02.633 GMT [7334] FATAL:  sorry, too many clients already
[...]
```
The last line is repeated every 4 to 10 seconds, so a large number of these.

## Memstore

Replica set include 3 pods, conatining each 2 containers: 1 redis and 1 sentinel.

### Memstore 0

#### Redis
  
Not much to see, expect a log stating:
```
1:M 16 Aug 15:19:59.435 * Partial resynchronization request from 100.96.2.61:6379 accepted. Sending 113726 bytes of backlog starting from offset 1306413738.
```

#### Sentinel

It rebooted a slave at one point:
```
1:X 16 Aug 07:00:25.675 * +slave slave 100.96.9.75:6379 100.96.9.75 6379 @ mymaster 100.96.7.229 6379
1:X 16 Aug 15:20:07.252 * +reboot slave 100.96.2.61:6379 100.96.2.61 6379 @ mymaster 100.96.7.229 6379
```

### Memstore 1 and 2

#### Redis

The first one restarted once (not sure if it was at init or during the compute)
No logs which looks useful.

### Sentinel

Nothing to see... But as redis the first one restarted once.

## Minio

OK

**Comment by gusmith** [comment]
Opened some issues after trying it: #407  and #408

**Comment by gusmith** [comment]
It has ran.
