### ISSUE TITLE
Issue with latest deployment

### ISSUE THREAD

**Issue by hardbyte** [data61/anonlink-entity-service#452]
`clkhash` CI tests against a deployment of anonlink-entity-service at testing.data61.xyz

Currently the tests are failing and the logs on the deployment show an error:

```
 [2019-10-16 02:02:31,681: INFO/ForkPoolWorker-107] Task entityservice.tasks.comparing.compute_filter_similarity[ea59bc43-b1b0-4803-9249-6a3de6c3e76f] succeeded in 0.12171111791394651s: (50, 1204, 'similarity-scores/8452f5d09bc9c114a61cba7e.bin')
[2019-10-16 02:02:31,681: ERROR/ForkPoolWorker-108] Chord callback for '622e3540-9ea1-4665-b017-d00dba9a084b' raised: AttributeError("module 'entityservice.errors' has no attribute 'InactiveRun'")
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/celery/backends/redis.py", line 399, in on_chord_part_return
    callback.delay([unpack(tup, decode) for tup in resl])
  File "/usr/lib/python3.7/site-packages/celery/backends/redis.py", line 399, in &lt;listcomp&gt;
    callback.delay([unpack(tup, decode) for tup in resl])
  File "/usr/lib/python3.7/site-packages/celery/backends/redis.py", line 350, in _unpack_chord_result
    retval = self.exception_to_python(retval)
  File "/usr/lib/python3.7/site-packages/celery/backends/base.py", line 276, in exception_to_python
    cls = getattr(sys.modules[exc_module], exc_type)
AttributeError: module 'entityservice.errors' has no attribute 'InactiveRun' 
```

Version info:
```
{
  "anonlink": "0.12.5",
  "entityservice": "v1.11.2",
  "python": "3.7.4"
}


chart: entity-service-1.11.4
```

**Comment by hardbyte** [comment]
I think the problem is we deployed with a `develop` tag, and on cluster changes the workers pulled a more recent docker image than the api

**Comment by hardbyte** [comment]
Now using a pinned version for the test deployment. Thanks for the fix @gusmith
