### ISSUE TITLE
Dataproviders can upload their clks mutilple times with the same upload_token

### ISSUE THREAD

**Issue by gusmith** [data61/anonlink-entity-service#462]
A data provider get an `upload_token` and can use it multiple times to upload multiple time clks.
An example of a project with 3 parties, the second party pushing twice its data.
```
  id  |                      token                       | uploaded |                     project                      |  id  |             ts             |  dp  |                      token                       |                               file                               | state | encoding_size | count 
------+--------------------------------------------------+----------+--------------------------------------------------+------+----------------------------+------+--------------------------------------------------+------------------------------------------------------------------+-------+---------------+-------
 3871 | 4ce1c1519b4cd709f548084d23f85326b5bb758bfd2532d3 | t        | 0d081bd6cb198ff27d5bb8b70d65c12fddfd2a6e5bb2cc9b | 2218 | 2019-11-06 06:56:18.471339 | 3871 | 86e8d71a6b9fa53bae0e8cb3e88d98686d1cac5d12cdd1b6 | raw-clks/86e8d71a6b9fa53bae0e8cb3e88d98686d1cac5d12cdd1b6.bin    | ready |           128 |  5000
 3872 | 45c68c1819a6968bbcfe8c341bc52f1425a335403159594a | t        | 0d081bd6cb198ff27d5bb8b70d65c12fddfd2a6e5bb2cc9b | 2219 | 2019-11-06 06:56:20.858782 | 3872 | 5d4a30558173e88f3ca003082b0d00b237894b129e2a6c49 | raw-clks/e741ca1ee0f0ba06c64a9151ef72d23fff216121f0db933e.bin    | ready |           128 |  5000
 3872 | 45c68c1819a6968bbcfe8c341bc52f1425a335403159594a | t        | 0d081bd6cb198ff27d5bb8b70d65c12fddfd2a6e5bb2cc9b | 2220 | 2019-11-06 07:07:10.882699 | 3872 | e741ca1ee0f0ba06c64a9151ef72d23fff216121f0db933e | raw-clks/e741ca1ee0f0ba06c64a9151ef72d23fff216121f0db933e.bin    | ready |           128 |  5000
(3 rows)
```

We can see that the token is the same, the data file is the same, but it is a new row in the database, because of which the run is triggered as it considered the three parties have provided their data.

But then, is creates some surprising error when the run actually runs:
```
worker_1   | [2019-11-06 07:58:40,093: ERROR/ForkPoolWorker-8] 2019-11-06T07:58:40.093394Z [error    ] Unexpected exception raised in task e6b3137b-d14e-4e49-a4c9-eae7894ba867 [entityservice.tasks] 
worker_1   | Traceback (most recent call last):
worker_1   |   File "/usr/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
worker_1   |     R = retval = fun(*args, **kwargs)
worker_1   |   File "/var/www/entityservice/tasks/base_task.py", line 87, in __call__
worker_1   |     return super(TracedTask, self).__call__(*args, **kwargs)
worker_1   |   File "/usr/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
worker_1   |     return self.run(*args, **kwargs)
worker_1   |   File "/var/www/entityservice/tasks/comparing.py", line 77, in create_comparison_jobs
worker_1   |     chunk_dp_store_filename = filters_object_filenames[chunk_dp_index]
worker_1   | IndexError: tuple index out of range
worker_1   | [2019-11-06 07:58:40,093: ERROR/ForkPoolWorker-8] Task entityservice.tasks.comparing.create_comparison_jobs[e6b3137b-d14e-4e49-a4c9-eae7894ba867] raised unexpected: IndexError('tuple index out of range')
worker_1   | Traceback (most recent call last):
worker_1   |   File "/usr/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
worker_1   |     R = retval = fun(*args, **kwargs)
worker_1   |   File "/var/www/entityservice/tasks/base_task.py", line 87, in __call__
worker_1   |     return super(TracedTask, self).__call__(*args, **kwargs)
worker_1   |   File "/usr/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
worker_1   |     return self.run(*args, **kwargs)
worker_1   |   File "/var/www/entityservice/tasks/comparing.py", line 77, in create_comparison_jobs
worker_1   |     chunk_dp_store_filename = filters_object_filenames[chunk_dp_index]
worker_1   | IndexError: tuple index out of range
```

**Comment by hardbyte** [comment]
Options?

I'm immediately thinking we shouldn't allow uploading more than once but should we consider any alternative solutions. E.g.
- use the most recent upload for each data provider... (which could change mid way through a run)

**Comment by gusmith** [comment]
IMHO, the best option would be to be able to post only once with a token. The other option would be to enable posting multiple times, enabling either versioning of the data or being able to update/overwrite it.

After a discussion with Wilko, the first option still seems better because we would either have to include a proper versioning of clks but we may not want to go there yet, or will need to think about it properly, or we would simply use the most recent upload, which would stop being able to repeat experiments as the underlying clks may change between runs.

**Comment by wilko77** [comment]
I'm for the upload once option too. Otherwise you would have to track the versioning of the clks through to the results. 
By carefully adjusting its clks between runs a dataprovider could potentially extract more information from the results than he should. This could be detected by pinning the results to the clk versions. 
But that's a lot of work for no extra functionality. Thus -> only upload once.
